# 
# Dockerfile to update extra python libraries:
# - ElasticSearch python client
#
# Tuan Tran
# ttran@L3S.de

FROM library/python

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

RUN pip install elasicsearch